### ISSUE TITLE
Explanation for pollBlockHits() in cheat-sheet not clear

### ISSUE THREAD

**Issue by luziferius** [foss-ag/workshop_minecraft-python#15]
https://github.com/foss-ag/workshop_minecraft-python/blob/7210ead34feae106419efb2314601e3aa2ca363f/cheat-sheet/cheat_sheet.tex#L138

What is this? This section is not clear at all:
It returns a list as the text below states? Why is it assigned to variable `hits` and then accessed as `hit`.
If it is a `list` type, its content should be accessed using the subscription operator `[]` and not using the field access with a `.` dot.

**Comment by ROYALBEFF** [comment]
That's true. Congratulations, you've found a mistake. hit is an object and not a position. But it's coordinates can be accessed by calling it's attributes pos.x, pos.y and pos.z.
Will be fixed soon ;)

**Comment by ROYALBEFF** [comment]
aaannnddd..... it's done :)
